/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "prdohxgymlaxypnslyag"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZG9oeGd5bWxheHlwbnNseWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzYyNDgsImV4cCI6MjA4ODI1MjI0OH0.oNzDZIABWyWqVAp6X2OUgKvK1B-Ew-D4ZxJjYwsEOUs"